#!/usr/bin/env bash

source "$(dirname "$BASH_SOURCE")/.validate"

IFS=$'\n'
files=( $(validate_diff --diff-filter=ACMR --name-only -- '*.go' | grep -v '^vendor/' || true) )
unset IFS

errors=()
failedErrcheck=$(errcheck .)
if [ "$failedErrcheck" ]; then
    errors+=( "$failedErrcheck" )
fi

if [ ${#errors[@]} -eq 0 ]; then
	echo 'Congratulations!  All Go source files have been errchecked.'
else
	{
		echo "Errors from errcheck:"
		for err in "${errors[@]}"; do
			echo "$err"
		done
		echo
		echo 'Please fix the above errors. You can test via "errcheck" and commit the result.'
		echo
	} >&2
	false
fi
