project_name: traefik

before:
  hooks:
    - go generate

builds:
  - binary: traefik

    main: ./cmd/traefik/
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/traefik/traefik/v3/pkg/version.Version={{.Version}} -X github.com/traefik/traefik/v3/pkg/version.Codename={{.Env.CODENAME}} -X github.com/traefik/traefik/v3/pkg/version.BuildDate={{.Date}}
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - '7'
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm

changelog:
  skip: true

archives:
  - id: traefik
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

release:
  disable: true
