---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static-config
data:
  static.yaml: |
    entryPoints:
      web:
        address: ':80'
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ':443'

    log:
      level: INFO

    api:
      dashboard: true

    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}
