#!/usr/bin/env bash
set -e

export REPO='containous/traefik'

if VERSION=$(git describe --exact-match --abbrev=0 --tags);
then
  export VERSION
else
  export VERSION=''
fi

export CODENAME=maroilles

export N_MAKE_JOBS=2


function ci_retry {

    local NRETRY=3
    local NSLEEP=5
    local n=0

    until [ $n -ge $NRETRY ]
    do
        "$@" && break
        n=$[$n+1]
        echo "$@ failed, attempt ${n}/${NRETRY}"
        sleep $NSLEEP
    done

    [ $n -lt $NRETRY ]

}

export -f ci_retry

