package types

const (
	LabelDomain                              = "traefik.domain"
	LabelEnable                              = "traefik.enable"
	LabelPort                                = "traefik.port"
	LabelPortIndex                           = "traefik.portIndex"
	LabelProtocol                            = "traefik.protocol"
	LabelTags                                = "traefik.tags"
	LabelWeight                              = "traefik.weight"
	LabelFrontendAuthBasic                   = "traefik.frontend.auth.basic"
	LabelFrontendEntryPoints                 = "traefik.frontend.entryPoints"
	LabelFrontendPassHostHeader              = "traefik.frontend.passHostHeader"
	LabelFrontendPriority                    = "traefik.frontend.priority"
	LabelFrontendRule                        = "traefik.frontend.rule"
	LabelFrontendRuleType                    = "traefik.frontend.rule.type"
	LabelTraefikFrontendValue                = "traefik.frontend.value"
	LabelTraefikFrontendWhitelistSourceRange = "traefik.frontend.whitelistSourceRange"
	LabelBackend                             = "traefik.backend"
	LabelBackendId                           = "traefik.backend.id"
	LabelTraefikBackendCircuitbreaker        = "traefik.backend.circuitbreaker"
	LabelBackendCircuitbreakerExpression     = "traefik.backend.circuitbreaker.expression"
	LabelBackendHealthcheckPath              = "traefik.backend.healthcheck.path"
	LabelBackendHealthcheckInterval          = "traefik.backend.healthcheck.interval"
	LabelBackendLoadbalancerMethod           = "traefik.backend.loadbalancer.method"
	LabelBackendLoadbalancerSticky           = "traefik.backend.loadbalancer.sticky"
	LabelBackendMaxconnAmount                = "traefik.backend.maxconn.amount"
	LabelBackendMaxconnExtractorfunc         = "traefik.backend.maxconn.extractorfunc"
)
