---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: cert-manager
stringData:
  cloudflare-token: YOUR_API_TOKEN
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: you@example.com
    solvers:
      - dns01:
          cloudflare:
            email: you@example.com
            apiTokenSecretRef:
              name: cloudflare-token
              key: cloudflare-token

