<template>
  <q-header>
    <q-toolbar>
      <q-toolbar-title>Header</q-toolbar-title>
    </q-toolbar>
  </q-header>
  <q-footer>
    <q-toolbar>
      <q-toolbar-title>Footer</q-toolbar-title>
    </q-toolbar>
  </q-footer>
</template>
