// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/middleware/grpc/message.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	ServerID             string            `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	RequestURI           string            `protobuf:"bytes,3,opt,name=RequestURI,proto3" json:"RequestURI,omitempty"`
	RemoteAddr           string            `protobuf:"bytes,4,opt,name=RemoteAddr,proto3" json:"RemoteAddr,omitempty"`
	Headers              map[string]string `protobuf:"bytes,5,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7f919522649f0eba, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetRequestURI() string {
	if m != nil {
		return m.RequestURI
	}
	return ""
}

func (m *Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Request) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type CancelRequest struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7f919522649f0eba, []int{1}
}
func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (dst *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(dst, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CancelRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Actions struct {
	SetRequestHeaders    map[string]string `protobuf:"bytes,1,rep,name=SetRequestHeaders,proto3" json:"SetRequestHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SetResponseHeaders   map[string]string `protobuf:"bytes,2,rep,name=SetResponseHeaders,proto3" json:"SetResponseHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RemoveRequestHeaders []string          `protobuf:"bytes,3,rep,name=RemoveRequestHeaders,proto3" json:"RemoveRequestHeaders,omitempty"`
	CancelRequest        *CancelRequest    `protobuf:"bytes,4,opt,name=CancelRequest,proto3" json:"CancelRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Actions) Reset()         { *m = Actions{} }
func (m *Actions) String() string { return proto.CompactTextString(m) }
func (*Actions) ProtoMessage()    {}
func (*Actions) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7f919522649f0eba, []int{2}
}
func (m *Actions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actions.Unmarshal(m, b)
}
func (m *Actions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actions.Marshal(b, m, deterministic)
}
func (dst *Actions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actions.Merge(dst, src)
}
func (m *Actions) XXX_Size() int {
	return xxx_messageInfo_Actions.Size(m)
}
func (m *Actions) XXX_DiscardUnknown() {
	xxx_messageInfo_Actions.DiscardUnknown(m)
}

var xxx_messageInfo_Actions proto.InternalMessageInfo

func (m *Actions) GetSetRequestHeaders() map[string]string {
	if m != nil {
		return m.SetRequestHeaders
	}
	return nil
}

func (m *Actions) GetSetResponseHeaders() map[string]string {
	if m != nil {
		return m.SetResponseHeaders
	}
	return nil
}

func (m *Actions) GetRemoveRequestHeaders() []string {
	if m != nil {
		return m.RemoveRequestHeaders
	}
	return nil
}

func (m *Actions) GetCancelRequest() *CancelRequest {
	if m != nil {
		return m.CancelRequest
	}
	return nil
}

type Response struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Actions              *Actions `protobuf:"bytes,2,opt,name=Actions,proto3" json:"Actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_7f919522649f0eba, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *Response) GetActions() *Actions {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterMapType((map[string]string)(nil), "grpc.Request.HeadersEntry")
	proto.RegisterType((*CancelRequest)(nil), "grpc.CancelRequest")
	proto.RegisterType((*Actions)(nil), "grpc.Actions")
	proto.RegisterMapType((map[string]string)(nil), "grpc.Actions.SetRequestHeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc.Actions.SetResponseHeadersEntry")
	proto.RegisterType((*Response)(nil), "grpc.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiddlewareClient is the client API for Middleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiddlewareClient interface {
	Handle(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type middlewareClient struct {
	cc *grpc.ClientConn
}

func NewMiddlewareClient(cc *grpc.ClientConn) MiddlewareClient {
	return &middlewareClient{cc}
}

func (c *middlewareClient) Handle(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Middleware/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServer is the server API for Middleware service.
type MiddlewareServer interface {
	Handle(context.Context, *Request) (*Response, error)
}

func RegisterMiddlewareServer(s *grpc.Server, srv MiddlewareServer) {
	s.RegisterService(&_Middleware_serviceDesc, srv)
}

func _Middleware_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Middleware/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).Handle(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Middleware_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Middleware",
	HandlerType: (*MiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _Middleware_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/middleware/grpc/message.proto",
}

func init() {
	proto.RegisterFile("api/middleware/grpc/message.proto", fileDescriptor_message_7f919522649f0eba)
}

var fileDescriptor_message_7f919522649f0eba = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x7e, 0xda, 0x09, 0x41, 0x30, 0x54, 0xc5, 0xf2, 0x01, 0x05, 0x0b, 0x44, 0xb8,
	0x38, 0x92, 0x41, 0x2a, 0xf4, 0x56, 0xd2, 0x4a, 0xed, 0x21, 0x42, 0xda, 0x28, 0x0f, 0x60, 0xb2,
	0xa3, 0x60, 0xe1, 0x78, 0xcd, 0x7a, 0x13, 0x94, 0xb7, 0xe2, 0xcd, 0x78, 0x05, 0xe4, 0xf5, 0x6e,
	0x88, 0x13, 0xf7, 0x90, 0xdb, 0xcc, 0x7c, 0x33, 0xdf, 0xce, 0x37, 0x33, 0x0b, 0x6f, 0xe2, 0x3c,
	0x19, 0xaf, 0x12, 0xce, 0x53, 0xfa, 0x1d, 0x4b, 0x1a, 0x2f, 0x65, 0xbe, 0x18, 0xaf, 0xa8, 0x28,
	0xe2, 0x25, 0x85, 0xb9, 0x14, 0x4a, 0x60, 0xbb, 0x8c, 0x05, 0x7f, 0x1d, 0xe8, 0x31, 0xfa, 0xb5,
	0xa6, 0x42, 0xa1, 0x0f, 0x67, 0x33, 0x92, 0x1b, 0x92, 0x0f, 0xb7, 0x9e, 0x33, 0x74, 0x46, 0xe7,
	0x6c, 0xe7, 0xe3, 0x25, 0x74, 0xa7, 0xa4, 0x7e, 0x08, 0xee, 0xb5, 0x34, 0x62, 0x3c, 0x7c, 0x0d,
	0x60, 0xca, 0xe7, 0xec, 0xc1, 0x73, 0x35, 0xb6, 0x17, 0xa9, 0xf0, 0x95, 0x50, 0x74, 0xc3, 0xb9,
	0xf4, 0xda, 0x16, 0xb7, 0x11, 0xfc, 0x04, 0xbd, 0x7b, 0x8a, 0x39, 0xc9, 0xc2, 0xeb, 0x0c, 0xdd,
	0x51, 0x3f, 0xf2, 0xc3, 0xb2, 0xaf, 0xd0, 0x50, 0x84, 0x06, 0xbc, 0xcb, 0x94, 0xdc, 0x32, 0x9b,
	0xea, 0x5f, 0xc3, 0xd3, 0x7d, 0x00, 0x9f, 0x83, 0xfb, 0x93, 0xb6, 0xa6, 0xe9, 0xd2, 0xc4, 0x0b,
	0xe8, 0x6c, 0xe2, 0x74, 0x4d, 0xa6, 0xdd, 0xca, 0xb9, 0x6e, 0x7d, 0x76, 0x82, 0x2b, 0x18, 0x4c,
	0xe2, 0x6c, 0x41, 0xa9, 0x95, 0x8d, 0xd0, 0x9e, 0x08, 0x4e, 0xba, 0xba, 0xc3, 0xb4, 0x5d, 0xc6,
	0xbe, 0x0a, 0xbe, 0x35, 0xd5, 0xda, 0x0e, 0xfe, 0xb8, 0xd0, 0xbb, 0x59, 0xa8, 0x44, 0x64, 0x05,
	0x32, 0x78, 0x31, 0x23, 0x65, 0x18, 0xac, 0x00, 0x47, 0x0b, 0x78, 0x5b, 0x09, 0x30, 0x99, 0xe1,
	0x51, 0x5a, 0x25, 0xe5, 0xb8, 0x1c, 0xe7, 0x80, 0x3a, 0x58, 0xe4, 0x22, 0x2b, 0xc8, 0x92, 0xb6,
	0x34, 0xe9, 0xbb, 0x06, 0xd2, 0x5a, 0x5e, 0xc5, 0xda, 0x40, 0x80, 0x11, 0x5c, 0x94, 0xf3, 0xde,
	0xd0, 0x41, 0xb7, 0xee, 0xd0, 0x1d, 0x9d, 0xb3, 0x46, 0x0c, 0xbf, 0x1c, 0xcc, 0x48, 0x2f, 0xae,
	0x1f, 0xbd, 0xac, 0xba, 0xa8, 0x41, 0xac, 0x9e, 0xe9, 0xdf, 0xc2, 0x65, 0xb3, 0xe4, 0x53, 0x96,
	0xe4, 0xdf, 0xc1, 0xab, 0x47, 0x34, 0x9e, 0xb4, 0xeb, 0x6f, 0x70, 0x66, 0x39, 0xca, 0xeb, 0x9e,
	0xa4, 0x09, 0x65, 0xea, 0xff, 0x75, 0x5b, 0x1f, 0xdf, 0xef, 0x36, 0xab, 0x39, 0xfa, 0xd1, 0xa0,
	0x36, 0x6f, 0x66, 0xd1, 0xe8, 0x0a, 0x60, 0xba, 0xfb, 0x55, 0xf8, 0x01, 0xba, 0xf7, 0x71, 0xc6,
	0x53, 0xc2, 0x41, 0xed, 0x6a, 0xfd, 0x67, 0xd6, 0xad, 0xde, 0x0e, 0x9e, 0x7c, 0xef, 0xea, 0x4f,
	0xf7, 0xf1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x07, 0xb8, 0x7c, 0x99, 0x03, 0x00, 0x00,
}
