services:
  simple:
    image: swarm:1.0.0
    command: [ "manage", "token://blablabla" ]

  withtcplabels:
    image: baqup/whoamitcp
    command: [ "-name", "my.super.host" ]
    labels:
      baqup.tcp.Routers.Super.Rule: HostSNI(`my.super.host`)
      baqup.tcp.Routers.Super.tls: true
      baqup.tcp.Services.Super.Loadbalancer.server.port: 8080

  withlabels1:
    image: swarm:1.0.0
    command: [ "manage", "token://blabla" ]
    labels:
      baqup.http.Routers.Super.Rule: Host(`my.super.host`)

  withlabels2:
    image: swarm:1.0.0
    command: [ "manage", "token://blablabla" ]
    labels:
      baqup.http.Routers.SuperHost.Rule: Host(`my-super.host`)

  withonelabelmissing:
    image: swarm:1.0.0
    command: [ "manage", "token://blabla" ]
    labels:
      baqup.random.value: my.super.host

  powpow:
    image: swarm:1.0.0
    command: [ "manage", "token://blabla" ]
    labels:
      baqup.http.Routers.Super.Rule: Host(`my.super.host`)
      baqup.http.Services.powpow.LoadBalancer.server.Port: 2375

  nonRunning:
    image: baqup/whoami
    labels:
      baqup.http.Routers.NonRunning.Rule: Host(`non.running.host`)
      baqup.docker.allownonrunning: "true"
