version: "3.8"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3.18
    command: etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2380

networks:
  default:
    name: traefik-test-network
    external: true
