services:
  etcd:
    image: quay.io/coreos/etcd:v3.3.18
    command: etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2380
    ports:
      - "2379:2379"
networks:
  default:
    external: true
    name: test-net
