services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    command:
      - etcd
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2380
