version: "3.8"
services:
  whoami1:
    image: traefik/whoami:v1.12.0

  whoami2:
    image: traefik/whoami:v1.12.0

  whoami3:
    image: traefik/whoami:v1.12.0

  whoami4:
    image: traefik/whoami:v1.12.0

  whoami5:
    image: traefik/whoami:v1.12.0
