version: "3.8"
services:
  server1:
    image: traefik/whoami
    labels:
      traefik.enable: true
      traefik.http.services.service1.loadbalancer.server.port: 80
      traefik.http.routers.router1.rule: Host(`github.com`)

networks:
  default:
    name: traefik-test-network
    external: true
