version: "3.8"
services:
  whoami1:
    image: traefik/whoami
    labels:
      traefik.http.Routers.RouterMini.Rule: PathPrefix(`/whoami`)
      traefik.enable: true
    deploy:
      replicas: 2

networks:
  default:
    name: traefik-test-network
    external: true
