services:
  pebble:
    image: letsencrypt/pebble:v2.3.1
    command:
      - pebble
      - --dnsserver
      - host.docker.internal:5053
    environment:
      # https://github.com/letsencrypt/pebble#testing-at-full-speed
      PEBBLE_VA_NOSLEEP: 1
      # https://github.com/letsencrypt/pebble#invalid-anti-replay-nonce-errors
      PEBBLE_WFE_NONCEREJECT: 0
