services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:2.8.0
    command:
      - --dnsserver
      - host.docker.internal:5053
    environment:
      # https://github.com/letsencrypt/pebble#testing-at-full-speed
      PEBBLE_VA_NOSLEEP: 1
      # https://github.com/letsencrypt/pebble#invalid-anti-replay-nonce-errors
      PEBBLE_WFE_NONCEREJECT: 0
