services:
  pebble:
    container_name: pebble
    image: letsencrypt/pebble:v2.3.1
    command: pebble --dnsserver traefik:5053
    ports:
      - 14000:14000
    environment:
      # https://github.com/letsencrypt/pebble#testing-at-full-speed
      - PEBBLE_VA_NOSLEEP=1
      # https://github.com/letsencrypt/pebble#invalid-anti-replay-nonce-errors
      - PEBBLE_WFE_NONCEREJECT=0
networks:
  default:
    external: true
    name: test-net
