version: "3.8"
services:
  haproxy:
    image: haproxy:2.2
    volumes:
      - traefik-test-configuration-volume:/usr/local/etc/haproxy/

  whoami:
    image: traefik/whoami

networks:
  default:
    name: traefik-test-network
    external: true

volumes:
  traefik-test-configuration-volume:
    external: true
