services:
  haproxy:
    image: haproxy:2.2
    volumes:
      - test-config:/usr/local/etc/haproxy/
  whoami:
    image: traefik/whoami
networks:
  default:
    external: true
    name: test-net
volumes:
  test-config:
    external: true
