services:
  whoami-a:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-a
      - -certFile
      - /certs/whoami-a.crt
      - -keyFile
      - /certs/whoami-a.key
    volumes:
      - ./fixtures/tcp:/certs

  whoami-b:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-b
      - -certFile
      - /certs/whoami-b.crt
      - -keyFile
      - /certs/whoami-b.key
    volumes:
      - ./fixtures/tcp:/certs

  whoami-ab:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-ab
      - -certFile
      - /certs/whoami-b.crt
      - -keyFile
      - /certs/whoami-b.key
    volumes:
      - ./fixtures/tcp:/certs

  whoami-no-cert:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-no-cert

  whoami-no-tls:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-no-tls

  whoami:
    image: baqup/whoami

  whoami-banner:
    image: baqup/whoamitcp
    command:
      - -name
      - whoami-banner
      - --banner
