version: "3.8"
services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./fixtures/tracing/tempo.yaml:/etc/tempo.yaml

  whoami:
    image: traefik/whoami

networks:
  default:
    name: traefik-test-network
    external: true
