services:
  zipkin:
    image: openzipkin/zipkin:2.16.2
    environment:
      STORAGE_TYPE: mem
      JAVA_OPTS: -Dlogging.level.zipkin=DEBUG
    ports:
      - 9411:9411
    network_mode: "bridge"
  jaeger:
    image: jaegertracing/all-in-one:1.14
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  whoami:
    image: traefik/whoami
    network_mode: "bridge"
