services:
  tempo:
    hostname: tempo
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./fixtures/tracing/tempo.yaml:/etc/tempo.yaml
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.0
    volumes:
      - ./fixtures/tracing/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  whoami:
    image: traefik/whoami
