version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin:2.24.3
    environment:
      STORAGE_TYPE: mem
      JAVA_OPTS: -Dlogging.level.zipkin=DEBUG

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./fixtures/tracing/tempo.yaml:/etc/tempo.yaml

  whoami:
    image: traefik/whoami

networks:
  default:
    name: traefik-test-network
    external: true
