apiVersion: gateway.networking.k8s.io/v1
date: "2026-10-08T09:46:33Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.6.3
implementation:
  contact:
  - '@traefik/maintainers'
  organization: traefik
  project: traefik
  url: https://traefik.io/
  version: v3.8
kind: ConformanceReport
mode: merged
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 14
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - GatewayInfrastructureMetadata
    statistics:
      Failed: 0
      Passed: 8
      Skipped: 1
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayPort8080
    - ListenerSet
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayStaticAddresses
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests partially succeeded with 1 test skips.
- core:
    result: partial
    skippedTests:
    - HTTPRouteMultipleGateways
    statistics:
      Failed: 0
      Passed: 35
      Skipped: 1
  extended:
    result: partial
    skippedTests:
    - GatewayInfrastructureMetadata
    statistics:
      Failed: 0
      Passed: 44
      Skipped: 1
    supportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayPort8080
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    - ListenerSet
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayStaticAddresses
    - HTTPRouteBackendTimeout
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
  name: GATEWAY-HTTP
  summary: Core tests partially succeeded with 1 test skips. Extended tests partially
    succeeded with 1 test skips.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 18
      Skipped: 0
  extended:
    result: partial
    skippedTests:
    - GatewayInfrastructureMetadata
    statistics:
      Failed: 0
      Passed: 8
      Skipped: 1
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayPort8080
    - ListenerSet
    - TCPRoute
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayStaticAddresses
  name: GATEWAY-TCP
  summary: Core tests succeeded. Extended tests partially succeeded with 1 test skips.
- core:
    result: partial
    skippedTests:
    - TLSRouteHostnameIntersection
    statistics:
      Failed: 0
      Passed: 18
      Skipped: 1
  extended:
    result: partial
    skippedTests:
    - GatewayInfrastructureMetadata
    statistics:
      Failed: 0
      Passed: 13
      Skipped: 1
    supportedFeatures:
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructure
    - GatewayPort8080
    - ListenerSet
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayStaticAddresses
  name: GATEWAY-TLS
  summary: Core tests partially succeeded with 1 test skips. Extended tests partially
    succeeded with 1 test skips.
