apiVersion: gateway.networking.k8s.io/v1
date: "2026-10-07T11:11:56+02:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.6.3
implementation:
  contact:
  - '@traefik/maintainers'
  organization: traefik
  project: traefik
  url: https://traefik.io/
  version: v3.7
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 14
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 4
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayInfrastructure
    - GatewayPort8080
    - GatewayStaticAddresses
    unsupportedFeatures:
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - ListenerSet
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 36
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 30
      Skipped: 0
    supportedFeatures:
    - BackendTLSPolicy
    - GatewayAddressEmpty
    - GatewayInfrastructure
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - BackendTLSPolicySANValidation
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 19
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 8
      Skipped: 0
    supportedFeatures:
    - GatewayAddressEmpty
    - GatewayInfrastructure
    - GatewayPort8080
    - GatewayStaticAddresses
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - ListenerSet
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
