#!/bin/bash
set -e

if ! test -e gen.go; then
	echo >&2 'error: generate must be run before binary'
	false
fi

rm -f dist/traefik

# Build binaries
CGO_ENABLED=0 go build -a -installsuffix nocgo -o dist/traefik .

