#!/usr/bin/env bash
set -e

export DEST=.

TESTFLAGS+=("-test.timeout=20m -failfast -v")

cd integration
echo "Testing against..."
docker version

# shellcheck disable=SC2086
# shellcheck disable=SC2048
go test -v ${TESTFLAGS[*]}
