#!/usr/bin/env bash
set -e

export DEST=.

TESTFLAGS+=("-test.timeout=20m -failfast")

if [ -n "${VERBOSE}" ]; then
    TESTFLAGS+=(-v)
elif [ -n "${VERBOSE_INTEGRATION}" ]; then
    TESTFLAGS+=(-v)
fi

cd integration
echo "Testing against..."
docker version

# shellcheck disable=SC2086
# shellcheck disable=SC2048
CGO_ENABLED=0 go test ${TESTFLAGS[*]}
