#!/usr/bin/env bash

source "$(dirname "$BASH_SOURCE")/.validate"

if grep -q "$(glide-hash)" glide.lock; then
	echo 'Congratulations! glide.lock is unchanged.'
else
	{
		echo "Error: glide.lock has been manually changed. Don't do this. Use script/glide.sh up instead."
		echo
	} >&2
	false
fi
