#!/bin/bash

source "$(dirname "$BASH_SOURCE")/.validate"

grep `glide-hash` glide.lock
if [ $? -eq 0 ]; then
	echo 'Congratulations! glide.lock is unchanged.'
else
	{
		echo "Error: glide.lock has been manually changed. Don't do this. Use glide up instead."
		echo
	} >&2
	false
fi
