
plugins:
  - checksum: 01ada5b1032deb07be8e1ba408885c2dfb12acf904a9f76f5290d788dacc04a3454ac851dfeee9dc09dfe7a1806d2cfa8593a93c5dcf60652c458608d43a307c
    path: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs
    spec: "https://github.com/CycloneDX/cyclonedx-node-yarn/releases/latest/download/yarn-plugin-cyclonedx.cjs"
