apiVersion: gateway.networking.k8s.io/v1
date: "2026-09-04T10:57:26+02:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.6.1
implementation:
  contact:
  - '@traefik/maintainers'
  organization: traefik
  project: traefik
  url: https://traefik.io/
  version: v3.7
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 15
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 1
      Skipped: 0
    supportedFeatures:
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - ListenerSet
  name: GATEWAY-GRPC
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 37
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 27
      Skipped: 0
    supportedFeatures:
    - BackendTLSPolicy
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests succeeded. Extended tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 20
      Skipped: 0
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 5
      Skipped: 0
    supportedFeatures:
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - TLSRouteModeMixed
    - TLSRouteModeTerminate
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayStaticAddresses
    - ListenerSet
  name: GATEWAY-TLS
  summary: Core tests succeeded. Extended tests succeeded.
succeededProvisionalTests:
- GRPCRouteNamedRule
- GatewayInfrastructure
- HTTPRoute303Redirect
- HTTPRoute307Redirect
- HTTPRoute308Redirect
- HTTPRouteNamedRule
- TLSRouteMixedTerminationSameNamespace
- TLSRouteTerminateSimpleSameNamespace
