{
 "kind": "discovery#restDescription",
 "etag": "\"bRFOOrZKfO9LweMbPqu0kcu6De8/tzwJjoO4XDFgwNQjmiM8lPsFMzA\"",
 "discoveryVersion": "v1",
 "id": "people:v1",
 "name": "people",
 "version": "v1",
 "revision": "20160210",
 "title": "Google People API",
 "description": "The Google People API service gives access to information about profiles and contacts.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/people/",
 "protocol": "rest",
 "baseUrl": "https://people.googleapis.com/",
 "basePath": "",
 "rootUrl": "https://people.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "version_module": true,
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/contacts": {
     "description": "Manage your contacts"
    },
    "https://www.googleapis.com/auth/contacts.readonly": {
     "description": "View your contacts"
    },
    "https://www.googleapis.com/auth/plus.login": {
     "description": "Know your basic profile info and list of people in your circles."
    },
    "https://www.googleapis.com/auth/user.addresses.read": {
     "description": "View your street addresses"
    },
    "https://www.googleapis.com/auth/user.birthday.read": {
     "description": "View your complete date of birth"
    },
    "https://www.googleapis.com/auth/user.emails.read": {
     "description": "View your email addresses"
    },
    "https://www.googleapis.com/auth/user.phonenumbers.read": {
     "description": "View your phone numbers"
    },
    "https://www.googleapis.com/auth/userinfo.email": {
     "description": "View your email address"
    },
    "https://www.googleapis.com/auth/userinfo.profile": {
     "description": "View your basic profile info"
    }
   }
  }
 },
 "resources": {
  "people": {
   "methods": {
    "get": {
     "id": "people.people.get",
     "path": "v1/{+resourceName}",
     "httpMethod": "GET",
     "description": "Provides information about a person resource for a resource name. Use `people/me` to indicate the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/user.addresses.read",
      "https://www.googleapis.com/auth/user.birthday.read",
      "https://www.googleapis.com/auth/user.emails.read",
      "https://www.googleapis.com/auth/user.phonenumbers.read",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile"
     ]
    },
    "getBatchGet": {
     "id": "people.people.getBatchGet",
     "path": "v1/people:batchGet",
     "httpMethod": "GET",
     "description": "Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/user.addresses.read",
      "https://www.googleapis.com/auth/user.birthday.read",
      "https://www.googleapis.com/auth/user.emails.read",
      "https://www.googleapis.com/auth/user.phonenumbers.read",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile"
     ]
    }
   },
   "resources": {
    "connections": {
     "methods": {
      "list": {
       "id": "people.people.connections.list",
       "path": "v1/{+resourceName}/connections",
       "httpMethod": "GET",
       "description": "Provides a list of the authenticated user's contacts merged with any linked profiles.",
       "scopes": [
        "https://www.googleapis.com/auth/contacts",
        "https://www.googleapis.com/auth/contacts.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
